### ISSUE TITLE
got successful message from apple, but failed by xcrun stapler staple command.

### ISSUE THREAD

**Issue by Macrow** [electron/electron-notarize#73]
I got the successful message from apple
```
electron-notarize notarzation done with info: {
  uuid: 'xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx',
  date: 2021-05-11T08:32:28.000Z,
  status: 'success',
  logFileUrl: 'https://osxapps-ssl.itunes.apple.com/itunes-assets/Enigma115/v4/e3/09/ab/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx/developer_log.json?accessKey=xxxxxxxxx',
  statusCode: 0,
  statusMessage: 'Package Approved'
} +3s
  electron-notarize notarization was successful +1ms
  electron-notarize attempting to staple app: /Users/macrow/Projects/xxx +0ms
```
the error message is:
```
electron-notarize:spawn cmd xcrun terminated with code: 66 +37ms
(node:49685) UnhandledPromiseRejectionWarning: Error: Failed to staple your application with code: 66

Processing: /Users/macrow/Projects/xxx
Properties are {
    NSURLIsDirectoryKey = 1;
    NSURLIsPackageKey = 0;
    NSURLIsSymbolicLinkKey = 0;
    NSURLLocalizedTypeDescriptionKey = Folder;
    NSURLTypeIdentifierKey = "public.folder";
    "_NSURLIsApplicationKey" = 0;
}
Stapler is incapable of working with Folder files.

    at /Users/macrow/Projects/xxx/node_modules/electron-notarize/src/index.ts:158:11
    at Generator.next (<anonymous>)
    at fulfilled (/Users/macrow/Projects/xxx/node_modules/electron-notarize/lib/index.js:4:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:49685) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:49685) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✨  Done in 599.73s.
```

what's wrong with the code? :(

**Comment by Macrow** [comment]
I don't know what happened.

Today, I try to notarize the app, the error message was gone!

So I'll close this issue.

**Comment by tinhnvc-gadget** [comment]
I had the same issue. Is there any solution? 
Thanks

**Comment by kruulik** [comment]
Ran into the same issue. No solutions found so far...

**Comment by kruulik** [comment]
@Macrow Any chance you could share your config? Here's mine:


```
// electron-builder.js
const {
  main,
  name,
  version,
  resources,
  description,
  displayName,
  author: _author,
} = require('./package.json');

const { getDevFolder } = require('./bin/utils');

const author = _author?.name ?? _author;
const currentYear = new Date().getFullYear();
const authorInKebabCase = author.replace(/\s+/g, '-');
const appId = `com.${authorInKebabCase}.${name}`.toLowerCase();

/** @type {import('electron-builder').Configuration} */
module.exports = {
  appId,
  productName: displayName,
  copyright: `Copyright © ${currentYear} — ${author}`,

  directories: {
    app: getDevFolder(main),
    output: `dist/v${version}`,
  },

  mac: {
    gatekeeperAssess: false,
    hardenedRuntime: true,
    entitlements: 'build/entitlements.mac.plist',
    entitlementsInherit: 'build/entitlements.mac.plist',
  },

  afterSign: 'scripts/notarize.js',

  dmg: {
    icon: false,
    sign: false,
  },

  linux: {
    category: 'Utilities',
    synopsis: description,
    target: ['AppImage', 'deb', 'pacman', 'freebsd', 'rpm'],
  },

  win: {
    icon: `${resources}/build/icons/icon.ico`,
    target: ['nsis', 'portable', 'zip'],
  },
};

```

```
// notarize.js
require('dotenv').config();
const { notarize } = require('electron-notarize');

exports.default = async function notarizing(context) {
  const { electronPlatformName, appOutDir } = context;
  if (electronPlatformName !== 'darwin') {
    return;
  }

  const appName = context.packager.appInfo.productFilename;

  return await notarize({
    tool: 'notarytool',
    appBundleId: `com.my-name.my-app`,
    appPath: `${appOutDir}/${appName}.app`,
    appleId: process.env.APPLE_ID,
    appleIdPassword: process.env.APPLE_ID_PASS,
    teamId: process.env.APPLE_TEAM_ID,
  });
};
```

```
// release.yml
on:
  push:
    tags: ['*']

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: apt-update
        if: startsWith(matrix.os, 'ubuntu-latest')
        run: sudo apt-get update

      - name: autoremove
        if: startsWith(matrix.os, 'ubuntu-latest')
        run: sudo apt autoremove

      - name: Install libarchive rpm on Linux
        if: startsWith(matrix.os, 'ubuntu-latest')
        run: sudo apt-get install libarchive-tools rpm

      - name: Release Electron app
        uses: coparse-inc/action-electron-builder@v1.0.0
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASS }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        with:
          github_token: ${{ secrets.github_token }}
          release: true

```
